# .goreleaser.yaml

project_name: codigo

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: codigo
    env:
      - CGO_ENABLED=0
    main: ./cmd/codigo
    ldflags:
      - -s -w -X "github.com/btwiuse/version.MajorString=0"
      - -s -w -X "github.com/btwiuse/version.MinorString=6"
      - -s -w -X "github.com/btwiuse/version.GitCommitString={{.Commit}}"
      - -s -w -X "github.com/btwiuse/version.GitTreeStateString=clean"
      - -s -w -X "github.com/btwiuse/version.GitVersionString={{.Version}}"
      - -s -w -X "github.com/btwiuse/version.BuildDateString={{.Date}}"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm64
      - windows_386
      - windows_amd64
      - windows_arm64
      - android_arm64

archives:
  - id: archive
    builds:
     - codigo
    files:
      - LICENSE
    name_template: >-
      {{ .ProjectName }}-{{- .Os }}-{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
